# core services
exec-once = waybar
exec-once = dunst
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = vicinae server

# wallpaper & display
exec-once = awww-daemon
exec-once = hyprctl dispatch focusmonitor DP-2
# set random wallpaper on startup
exec-once = awww img $(find ~/wallpapers/ -type f | shuf -n 1)

# external settings
exec = ~/.config/ml4w-hyprland-settings/hyprctl.sh

# clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
