hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })
hl.gesture({ fingers = 3, direction = "up", action = function() hl.exec_cmd("quickshell ipc -p /home/elyes/apps/qs-hyprview call expose toggle 'smartgrid'") end })
